model:
  lr: 0.01
  dlr: 0.001
  mixed_data: False
  lambda1: 2000
  lambda2: 0.0001
  nh: 20
  dnh: 200
  train_epochs: 3000
  test_epochs: 1000
  batch_size: -1
  losstype: "wgan"
  dagloss: True
  dagstart: 0.5
  dagpenalization: 0
  dagpenalization_increase: 0.01
  functional_complexity: 'l2_norm'
  hlayers: 2
  dhlayers: 2
  sampling_type: 'sigmoidproba'
  linear: False
  optimizer_type: "RMSprop"
  n_discr: 8
  resample: True
  nruns: 1
  njobs: 1
  verbose: True

data:
  _target_: cdt.data.AcyclicGraphGenerator
  causal_mechanism: 'gp_mix'
  # noise: 'uniform'
  # noise_coeff: 0.4
  # npoints: 500
  nodes: 5
  parents_max: 2
  # expected_degree: 3
  # dag_type: 'default'

hydra:
  launcher:
    timeout_min: 60
    cpus_per_task: 1
    gpus_per_node: 0
    tasks_per_node: 1
    mem_gb: 32
    name: ${hydra.job.name}
    partition: cpu_med
    array_parallelism: 32
  job:
    env_set:
      MKL_THREADING_LAYER: GNU
      MKL_SERVICE_FORCE_INTEL: '1'
      # CUDA_VISIBLE_DEVICES: '0,1

seeds: 1

defaults:
  - override hydra/launcher: submitit_slurm