model:
  lr: 0.01
  dlr: 0.001
  mixed_data: False
  lambda1: 10
  lambda2: 0.001
  nh: 20
  dnh: 200
  train_epochs: 3000
  test_epochs: 1000
  batch_size: -1
  losstype: "fgan"
  dagloss: True
  dagstart: 0.5
  dagpenalization: 0
  dagpenalization_increase: 0.01
  functional_complexity: 'l2_norm'
  hlayers: 2
  dhlayers: 2
  sampling_type: 'sigmoidproba'
  linear: False
  nruns: 1
  verbose: True
data:
  _target_: cdt.data.AcyclicGraphGenerator
  causal_mechanism: 'nn'
  noise: 'gaussian'
  noise_coeff: 0.4
  npoints: 1000
  nodes: 10
  parents_max: 2
  expected_degree: 3
  dag_type: 'default'